# Change these first
owner: WoiluID # Your GitHub organization or username, where this repository lives
repo: Woilu-Status # The name of this repository

sites:
  - name: Woilu
    url: https://woilu.com
  - name: Woilu Shortlink
    url: https://woilu.net
  - name: Al Khwarizmi Link Tree
    url: https://woilu.org
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true
  
assignees: # Users to assign downtime issues (optional)
  - AzharRizkiZ
  - AzharRizky

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.woilu.com
  # baseUrl: /your-repo-name
  logoUrl: https://woilu.net/assets/images/Woilu.png
  name: Woilu Website Status
  introTitle: "**Woilu** is part of Mineversal & owned by Al Khwarizmi."
  introMessage: This is a status page which uses **real-time** data from our [Woilu Status](https://github.com/WoiluID/Woilu-Status). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Creator
      href: https://woilu.com
  favicon: https://woilu.net/assets/images/favicon.ico
  theme: light
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
